### PR TITLE
Set canRoam to false so assigned node works properly

### PR DESCRIPTION
**Pull request by ramereth**
Otherwise this tries to run on any node and that's not intended.

### CODE REVIEW

**Comment by knightsamar** [comment]
So if it fails to run on a node, it just gives up. I thought it would try running again on the actual intended node after some time?

**Comment by ramereth** [comment]
@knightsamar When you select a node via the interface this additional XML field gets added. However I missed that when I added the assignedNode before. If you look at the other Jenkins job templates in the repo, you'll notice the same thing.

**Comment by knightsamar** [comment]
If this value can be set in a default template, I think it would be apt to do it there too.

**Comment by ramereth** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.1.4.  Have a nice day!

**Pull request merged**
