### PR TITLE
Update matrix-auth and cloudbees-folder for security issues

### PR DESCRIPTION
**Pull request by ramereth**
These two plugins need to be upgraded prior to merging #179 due some dependency
issues.

### CODE REVIEW

**Comment by ramereth** [comment]
!bump patch *

**Comment by ramereth** [comment]
!bump patch *

**Comment by ramereth** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.4.1.  Have a nice day!

**Pull request merged**
