### PR TITLE
Update ruby paths in scripts to Cinc ruby

### PR DESCRIPTION
**Pull request by detjensrobert**

### CODE REVIEW

**Comment by ramereth** [comment]
!bump patch *

**Comment by ramereth** [comment]
!bump patch *

**Comment by ramereth** [comment]
!bump patch *

**Comment by ramereth** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v2.8.2.  Have a nice day!

**Pull request merged**
