### PR TITLE
Jenkins scripts and logic for automatically updating/checking the zonefiles

### PR DESCRIPTION
**Pull request by ramereth**
This is the jobs and scripts that will do the following:

- [x] update-zonefiles Jenkins job to be run on the DNS Master.
- [x] checkzone ruby script to check the syntax of named zone files. It also comments the PR if an error has occured and includes the error output from named-checkzone.
- [x] checkzone Jenkins job to be run when PR's are created and/or updated.
- [x] ChefSpec tests
- [x] ServerSpec tests

### CODE REVIEW

**Comment by ramereth** [comment]
[Jenkins scripts and logic for automatically updating/checking the zonefiles](https://trello.com/c/XDo20PV7/332-jenkins-scripts-and-logic-for-automatically-updating-checking-the-zonefiles)

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs this is ready for initial review however this includes the commit from #56 so please ignore that code and review it on that PR.

**Comment by ramereth** [comment]
@knightsamar yes

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs can I please get some review on this now?

**Comment by ramereth** [comment]
@knightsamar look at the documentation just above the cookbook-uploader test-kitchen suite. We probably should move this to the README to make it more apparent but you need to set a few environment variables to get this to converge properly unfortunately.

**Comment by knightsamar** [comment]
bumpzone-centos-73 passes.

**Comment by ramereth** [comment]
@knightsamar does that mean this gets your shiny :star: of approval? :smiley:

**Comment by knightsamar** [comment]
`bumpzone-centos-73` Verified
`github-comment-centos-68` Verified
`github-comment-centos-73` Verified

**Comment by knightsamar** [comment]
`bumpzone-centos-68` runs into https://pastebin.osuosl.org/49556/72612014/ but as you say it's broken because of various things, I can choose to ignore it and approve.

**Comment by ramereth** [comment]
@knightsamar I've had that happen before and have no idea what causes that. If you run converge again it usually works fine.

**Comment by knightsamar** [comment]
Converges. I had given up after multiple ssh timeouts! :)

**Comment by ramereth** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.1.0.  Have a nice day!

**Pull request merged**
