### PR TITLE
Install SGE jenkins plugin on powerci

### PR DESCRIPTION
**Pull request by ramereth**
This installs the sge-cloud-plugin directly from the URL since it's not
searchable in the plugin database for some reason.

### CODE REVIEW

**Comment by ramereth** [comment]
[POWER CI: Add SGE Cloud Plugin](https://trello.com/c/XWWvwiDT/657-power-ci-add-sge-cloud-plugin)

**Comment by ramereth** [comment]
@Codysseus make sure you remove ``Berksfile.lock`` and try again.

**Comment by Codysseus** [comment]
Ugh, now I'm running into an issue where it fails when creating jenkins_password_credentials.
```
ArgumentError
       -------------
       You must supply a name when declaring a jenkins_password_credentials resource
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/osl-jenkins/recipes/master.rb:96:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/osl-jenkins/recipes/master.rb:95:in `each'
         /tmp/kitchen/cache/cookbooks/osl-jenkins/recipes/master.rb:95:in `from_file'
         /tmp/kitchen/cache/cookbooks/osl-jenkins/recipes/powerci.rb:118:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/osl-jenkins/recipes/master.rb:
       
        89:  secrets = credential_secrets
        90:  
        91:  # This is necessary in order to create Jenkins jobs with security enabled.
        92:  node.run_state[:jenkins_private_key] = secrets['jenkins_private_key'] # ~FC001
        93:  
        94:  # Add git credentials into Jenkins
        95:  secrets['git'].to_a.each do |git_id, cred|
        96>>   jenkins_password_credentials cred['user'] do
        97:      id git_id
        98:      password cred['token']
        99:    end
       100:  end
       101:  
       102:  # Add ssh credentials into Jenkins
       103:  secrets['ssh'].to_a.each do |ssh_id, cred|
       104:    jenkins_private_key_credentials cred['user'] do
       105:      id ssh_id
```

**Comment by ramereth** [comment]
@Codysseus it's not your fault, this suite is special. Please look over the README for what you need to do which is set a few environment variables and create some oauth tokens on github.

**Comment by Codysseus** [comment]
Now once it reaches the `safe_restart` jenkins command in `osl-jenkins::master`, it throws an error saying "Bad Credentials". I am working on figuring that out, I just wanted to give you an update.

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs is anyone else having this problem?

**Comment by ramereth** [comment]
@Codysseus final review?

**Comment by Codysseus** [comment]
I don't know what's wrong, but I can't get it to converge :/

**Comment by ramereth** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.9.17.  Have a nice day!

**Pull request merged**
