### PR TITLE
Update osl-haproxy version

### PR DESCRIPTION
**Pull request by andrewda**

### CODE REVIEW

**Comment by andrewda** [comment]
@ramereth before merging, should I remove the branch in the Berksfile? (since manatee automatically deleted it after the osl-haproxy PR was merged)

**Comment by ramereth** [comment]
@andrewda ah yes!

**Comment by andrewda** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.7.0.  Have a nice day!

**Comment by andrewda** [comment]
^ will add osl-haproxy bump to that chef-repo PR

**Pull request merged**
