### PR TITLE
Update to Jenkins 2.164.1 and bump upstream cookbook to latest

### PR DESCRIPTION
**Pull request by ramereth**
Also bump plugins and upstream cookbook to latest version.

### CODE REVIEW

**Comment by ramereth** [comment]
[Update to Jenkins 2.164.1 and bump upstream cookbook to latest](https://trello.com/c/WOyv9rdO/1213-update-to-jenkins-21641-and-bump-upstream-cookbook-to-latest)

**Comment by ramereth** [comment]
@TravisWhitehead we updated chefdk a while ago and we hadn't touched this cookbook since then. I'll fix that.

**Comment by ramereth** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.1.0.  Have a nice day!

**Pull request merged**
