### PR TITLE
install gems directly

### PR DESCRIPTION
**Pull request by TheREK3R**

### CODE REVIEW

**Comment by ramereth** [comment]
[osl-jenkins: install gems directly instead of with attribute](https://trello.com/c/TCuiwD7g/1894-osl-jenkins-install-gems-directly-instead-of-with-attribute)

**Review by ramereth — APPROVED** [review]
Please do a minor bump.

**Comment by TheREK3R** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.11.0.  Have a nice day!

**Pull request merged**
