### PR TITLE
Bump yum-versionlock cookbook version

### PR DESCRIPTION
**Pull request by detjensrobert**
No other changes needed to use the latest version.

### CODE REVIEW

**Comment by detjensrobert** [comment]
[Idempotency fixes for yum-plugin-versionlock dependents](https://trello.com/c/WcFyE6EK/2060-idempotency-fixes-for-yum-plugin-versionlock-dependents)

**Review by ramereth — APPROVED** [review]
Please do a minor bump when you do this.

**Comment by detjensrobert** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.12.0.  Have a nice day!

**Pull request merged**
