### PR TITLE
Move .git-credentials and jenkins credential management into master recipe

### PR DESCRIPTION
**Pull request by ramereth**
This moves managment of .git-credentials and jenkins tokens centrally instead as
a one-off in the cookbook uploader recipe. This allows reuse for future jenkins
jobs we may use in the future.

Other changes or enhancements:

- Moved secrets management to a library credential_secrets
- Added basic ChefSpec tests for master and cookbook_uploader recipes
  (incomplete however)

This depends on #49 before merging and will be rebased after that is merged. This contains a single commit so you can see what change I'm really making for this.

### CODE REVIEW

**Comment by ramereth** [comment]
I need to refactor this a bit as I just discovered a better way to manage this directly with jenkins. For now hold on reviewing this.

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs ready for review

**Comment by ramereth** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v0.9.0.  Have a nice day!

**Pull request merged**
