### PR TITLE
add packer_pipeline job

### PR DESCRIPTION
**Pull request by knightsamar**

### CODE REVIEW

**Comment by knightsamar** [comment]
kitchen fails for me on jenkins1 due to a problem with getting secrets for `cookbook_uploader`
Stacktrace: https://pastebin.osuosl.org/62771/

[kitchen diagnose](https://pastebin.osuosl.org/62766/) shows  that kitchen does find the right variables from [bash exports](https://pastebin.osuosl.org/62761/)

**Comment by knightsamar** [comment]
using actual token (with repo: access) and my actual user name  does not fix the convergence failure. Does it work for you?

**Comment by ramereth** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.8.4.  Have a nice day!

**Pull request merged**
